services:
  agency-bot:
    # OLD: build: .
    # NEW: Download from Docker Hub (where GitHub Actions pushes)
    image: jaikumargaja/agency-bot:latest
    container_name: bitforge_bot_prod
    env_file:
      - .env
    volumes:
      - ./agency-data:/data
    restart: always

  # Add the Watchtower Service here
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 # Check for updates every 30 seconds
