services:
  agency-bot:
    build: .   # Make sure this is "build", not "image" for now
    container_name: bitforge_web
    env_file:
      - .env
    ports:
      - "5000:5000"  # Left: Laptop Port, Right: Container Port
    volumes:
      - ./agency-data:/data
